spring.application.name=be-foodgo
server.port=8086

# JWT Configuration
jwt.secret=FoodGoJwtSecretKey2026Nam3Ki2VeryLongAndSecure256BitSecretKeyForSigningTokens
jwt.expiration=10800000
jwt.refresh-expiration=2592000000
jwt.bearer-prefix=Bearer

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=foldershop83@gmail.com
spring.mail.password=yhuz zsmd kgem tmbt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Enable/disable real email sending (set to false in dev to fall back to console)
app.email.enabled=true
